baseurl = "/"
languageCode = "fr-fr"
languageLang = "fr"
title = "Psychologue pour Enfants"

# RSS, categories and tags disabled for an easy start
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
images = ["img/og-image.jpg"]