backend:
  name: git-gateway
  branch: main

media_folder: "site/static/img"
public_folder: "img"

collections:
  - name: "post"
    label: "Articles"
    folder: "site/content/post"
    path: "{{slug}}/index"
    create: true
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date de publication", name: "date", widget: "datetime"}
      - {label: "Résumé", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Contenu", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Page d'accueil"
        name: "home"
        fields:
          - {label: "Titre", name: "title", widget: "string"}
          - {label: "Sous-titre", name: "subtitle", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Introduction", name: "intro", widget: "object", fields: [
              {label: "Titre", name: "heading", widget: "string"},
              {label: "Texte", name: "text", widget: "text"}]}
      - file: "site/content/contact/_index.md"
        label: "Page de contact"
        name: "contact"
        fields:
          - {label: "Titre", name: "title", widget: "string"}
          - {label: "Logo", name: "logo", widget: "image"}
          - {label: "Contenu", name: "body", widget: "markdown"}
          - label: "Entrées de contact"
            name: contact_entries
            widget: list
            fields:
              - label: "Titre"
                name: "heading"
                widget: "string"
              - label: "Texte"
                name: "text"
                widget: "text"}
      - file: "site/content/values/_index.md"
        label: "Page des valeurs"
        name: "values"
        fields:
          - {label: "Titre", name: "title", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}
          - label: "Valeurs"
            name: values
            widget: list
            fields:
              - {label: "Titre", name: "heading", widget: "string"}
              - {label: "Texte", name: "text", widget: "text"}
              - {label: "Image", name: "imageUrl", widget: "image"}
  - name: "site_settings"
    label: "Site Settings"
    files:
      - file: "site/data/footer.json"
        label: Footer
        name: footer
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Blurb, name: blurb, widget: text}
      - file: "site/hugo.toml"
        label: Hugo Config
        name: config
        editor:
          preview: false
        fields:
          - {label: Site Title for Browser Tab, name: title, widget: string}
          - label: Params
            name: params
            widget: object
            fields:
              - label: Open Graph Image
                name: images
                widget: list
                field: { label: Image, name: image, widget: image }
